version: '3'
services:
  postgres_api:
    container_name: postgres_api
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - ./evolution_postgres:/var/lib/postgresql/data
    env_file:
      - db.env

  evolution_api2:
    container_name: evolution_api2
    image: evoapicloud/evolution-api
    restart: always
    ports:
      - "7777:8080"
    env_file:
      - evolution.env
    volumes:
      - ./evolution_instances:/evolution/instances
      - ./evolution_store:/evolution/store
    expose:
      - 7777
    depends_on:
      - postgres_api

# volumes:
#  evolution_store:
#  evolution_instances: